server:
  port: 8181

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    #    show-sql: true # ?? ??? ??? ???? ??
    # ??? ?? ? ?? ??? ?? ???? ??
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # sql ? ????? ??? ??
    database: mysql
  # file max size limit
  servlet:
    multipart:
      max-file-size: 10MB # each file max size
      max-request-size: 20MB # full request max size

logging.level:
  org.hibernate.SQL: debug # ? ? ??? ????? ???? ?? ?? ??? ? ? ??.

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: FdU3DlUyPt9/QikVJPodSp3SDU7h0602uyN754mPIsKQO3bG0Hr+srp/ZpCZiXAnStxt4WP6RNnw1vpiWYwuFg==

# 업로드파일 저장 위치
upload:
  path: C:/intellij_projects/todo_upload

# aws 설정
cloud:
  aws:
    s3:
      bucket: my.first.example.sss.bucket
    credentials:
      access-key: AKIA4LMXKQQFGT365H7R
      secret-key: SpmcRDmbpr+NrCRxfCSMVucuV5LaMZ0QV4HJvygk
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# s3 접근 설정
aws:
  credentials:
    accessKey: AKIAWTIOGNSVM4JCSVME
    secretKey: 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
  region: ap-northeast-2
  bucketName: s3-bucket-admin-jhlee